### ISSUE TITLE
Shebang has too many arguments

### ISSUE THREAD

**Issue by prupert** [regilero/check_nginx_status#16]
The script `check_nginx_status.pl` fails on CentOS 7 (and most likely on other Linux distros as well) with the following error:
```
/usr/bin/env: perl -w: No such file or directory
```

This is due to having more than one argument in the shebang command (`perl` and `-w`):
```
#!/usr/bin/env perl -w
```

These will work just fine:
```
#!/usr/bin/env perl
#!/usr/bin/perl -w
```

I propose that you drop the `-w` and add `use warnings;` in the Perl script. In that case you can still use `env perl` to maintain compatibility on servers with custom paths to `perl`.

**Comment by regilero** [comment]
It looks like the right thing to do, yes. Keeping the "env" is better.

Maybe you could make a Pull Request with these elements? This way you'll be granted for the fix, (and it would also save some time for me :-) )

**Comment by prupert** [comment]
There you go! ;-)

**Comment by regilero** [comment]
Should be fixed by last commits
