### ISSUE TITLE
#!/usr/bin/env perl -w in Ubuntu 16.04

### ISSUE THREAD

**Issue by devdesco-ceo** [regilero/check_nginx_status#17]
`#!/usr/bin/env perl -w` on line 1 for Ubuntu 16.04 is wrong.
>/usr/lib/nagios/plugins/check_nginx_status
/usr/bin/env: ‘perl -w’: No such file or directory

I changed it to `#!/usr/bin/perl -w` and it works as expected.
>/usr/lib/nagios/plugins/check_nginx_status
Usage: ./check_nginx_status -H <host ip> [-p <port>] [-s servername] [-t <timeout>] [-w <WARN_THRESOLD> -c <CRIT_THRESOLD>] [-V] [-d] [-u <url>] [-U user -P pass -r realm]
NGINX UNKNOWN - -H host argument required

>/usr/lib/nagios/plugins/check_nginx_status -H 192.168.2.1:88
> NGINX OK -  0.060 sec. response time, Active: 3 (Writing: 1 Reading: 0 Waiting: 2) ReqPerSec: 0.000 ConnPerSec: 0.000 ReqPerConn: 1.252|Writing=1;;;; Reading=0;;;; Waiting=2;;;; Active=3;;;; ReqPerSec=0.000000;;;; ConnPerSec=0.000000;;;; ReqPerConn=1.252177;;;;

Thank you for amazing module!!!

**Comment by regilero** [comment]
Certainly linked with #16

**Comment by regilero** [comment]
Should be fixed by last commits.
