### ISSUE TITLE
Check nginx - error 503

### ISSUE THREAD

**Issue by Quentinvarquet** [regilero/check_nginx_status#19]
Hello,

I have an ubuntu 10 server.

Nginx is active but when I use your script : 

./check_nginx_status.pl -H localhost

I have this error : NGINX CRITICAL - 503 error service unavailable

Do you know why ?

**Comment by regilero** [comment]
The first thing you need to check is that you can access the nginx-status page, without the monitoring script.

You can find docs online for that, like http://www.queryadmin.com/884/enable-nginx-status-page/

When you are sure that this location exists and could be accessed the goal is to use all the options of this monitoring script to access the right url, on the right domain.

The fact you have a 503 means the default location for this page (which is /nginx_status), on the given host (here http://localhost/nginx_status) is not rendering the status page (it should be a text page with several counters).

**Comment by Quentinvarquet** [comment]
Hello,

I forgot to close my issue. The status page was... disable :-) 

Thank you for your answer !
